---
title: Rezeptbuch
description: Sammlung von Koch- und Backrezepten zur einfachen Suche und zum nachkochen!
theme: just-the-docs
url: https://OlGe404.github.io/rezeptbuch

aux_links_new_tab: true
aux_links:
  "Rezept hinzufügen":
    - "https://github.com/OlGe404/OlGe404.github.io/blob/main/README.md#hinzuf%C3%BCgen-neuer-rezepte"

search:
  rel_url: false
  heading_level: 3
  previews: 5
  preview_words_after: 5

exclude:
  - .github
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - renovate.json
  - to-dos.md
