---
title: Rezeptbuch
description: Sammlung von Rezepten zur einfachen Suche und zum nachkochen!
theme: just-the-docs
url: https://OlGe404.github.io/rezeptbuch

aux_links_new_tab: true
aux_links:
  "Quellcode auf GitHub":
    - "https://github.com/OlGe404/OlGe404.github.io"

search:
  rel_url: false
  heading_level: 3
  previews: 5
  preview_words_after: 5

exclude:
  - Makefile
  - LICENSE
  - README.md
  - to-dos.md
