---
title: Rezeptbuch
description: Sammlung von Koch- und Backrezepten zur einfachen Suche und zum nachkochen!
theme: just-the-docs
url: https://OlGe404.github.io/rezeptbuch
aux_links:
  "Startseite":
    - /

search:
  rel_url: false
  heading_level: 3
  previews: 5
  preview_words_after: 5

callouts:
  info:
    title: Info
    color: blue

  warning:
    title: Achtung
    color: yellow

exclude:
  - .github
  - .gitignore
  - .ruby-version
  - converter.py
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - python3-venv.sh
  - README.md
  - renovate.json
  - requirements.txt
  - to-dos.md
